# Generated by Django 5.0.6 on 2024-06-25 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erstellt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('datum', models.DateField(default=datetime.date.today)),
                ('uuid', models.CharField(max_length=33, unique=True)),
            ],
            options={
                'ordering': ['datum'],
            },
        ),
        migrations.CreateModel(
            name='Kontrollen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('identifier', models.CharField(default='', help_text='Name, welchen die Python Dateien besitzen (ohne .py)', max_length=300, unique=True)),
                ('fach', models.CharField(default='Mathematik', max_length=100)),
                ('thema', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('jahrgang', models.IntegerField()),
                ('sichtbar', models.BooleanField(default=True)),
                ('beispiel', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
