# Generated by Django 5.1 on 2024-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stufe', models.CharField(choices=[('Primärstufe', 'Primärstufe'), ('Mittelstufe', 'Mittelstufe'), ('Oberstufe', 'Oberstufe')], max_length=100)),
                ('fach', models.CharField(default='Mathematik', max_length=100)),
            ],
        ),
    ]
