# Generated by Django 5.1b1 on 2024-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aufgaben', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themen',
            name='stufe',
            field=models.CharField(choices=[('Mittelstufe', 'Mittelstufe'), ('Oberstufe', 'Oberstufe')], default='Oberstufe', max_length=100),
        ),
    ]
