# Generated by Django 5.1b1 on 2024-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aufgaben', '0002_themen_stufe'),
    ]

    operations = [
        migrations.AddField(
            model_name='themen',
            name='fach',
            field=models.CharField(default='Mathematik', max_length=100),
        ),
    ]
